language: objective-c
osx_image: xcode8

env:
  global:
    - WORKSPACE=EventLogger.xcworkspace
    - IOS_SCHEME=EventLogger
    - SDK=iphonesimulator
    - CONFIG="Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES"
  matrix:
    - SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK" DESTINATION="OS=9.2,name=iPhone 6"
    - SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK" DESTINATION="OS=9.3,name=iPhone 6S Plus"
    - SCHEME="$IOS_SCHEME"  SDK="$IOS_SDK" DESTINATION="OS=10.0,name=iPhone 7"

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration $CONFIG test | xcpretty -c;
