language: objective-c
osx_image: xcode8.3

env:
  global:
    - WORKSPACE=EventLogger.xcworkspace
    - IOS_SCHEME=EventLogger
    - CONFIG="Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES"
  matrix:
    - SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" DESTINATION="OS=9.0,name=iPhone 5"
    - SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" DESTINATION="OS=10.3,name=iPhone 7 Plus"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -destination "$DESTINATION" -configuration $CONFIG | xcpretty -c;
